### PR TITLE
#4 Gradients added

### PR DESCRIPTION
**Pull request by pani-vishal**
#4 
Gradients have been added.
Now the user can select gradients by passing 1 to 23 as an argument while calling CreateSquare, CreateLand or CreatePort. This is optional of course. If no argument is passed the 1st gradient is selected by default.

### CODE REVIEW

**Comment by gauthamzz** [comment]
screenshot

**Comment by pani-vishal** [comment]
Sorry, sending right away. :sweat_smile:

**Comment by pani-vishal** [comment]
I only used CreatePort for the examples,others work similarly.
go1
Here no argument was passed.
go2
Here argument was passed but it was the first gradient so it's the same as before, therefore gradients must be indexed from 1.
go3
Argument passed and accordingly the gradient was chosen.

**Comment by gauthamzz** [comment]
travis errors

**Comment by pani-vishal** [comment]
How do I get past them?

**Comment by mubaris** [comment]
Use one main function. That means combine all examples to pass Travis errors

**Review by mubaris — CHANGES_REQUESTED** [review]
Clear Travis Errors

**Comment by pani-vishal** [comment]
Alright! I'll make a single example file and call all the functions once.

**Comment by mubaris** [comment]
I have updated the examples. I'm closing this. Send another PR with each updated examples in separate folders inside `examples` directory.

**Comment by pani-vishal** [comment]
Alright. Will do.

**Pull request closed without merging**
